//
//  questionBank.swift
//  Quiz for Kids
//
//  Created by Amru Hashim on 2/21/24.
//

let questionBank: [String: [Details]] = [
    
    "Animals": [
            Details(question: "Many ____ make venom, or poison, that they shoot into their prey.",
                    correctAns: 3,
                    option1ImageName: "sloth",
                    option2ImageName: "koala",
                    option3ImageName: "snake",
                    option4ImageName: "frog"),
            Details(question: "A ____ lives in a pack and can howl loudly?",
                    correctAns: 4,
                    option1ImageName: "lion",
                    option2ImageName: "tiger",
                    option3ImageName: "cheetah",
                    option4ImageName: "wolf"),
            Details(question: "The last _____ died about 65.5 million years ago.", 
                    correctAns: 2, 
                    option1ImageName: "rhino",
                    option2ImageName: "dinosaur",
                    option3ImageName: "lion",
                    option4ImageName: "wolf"),
            Details(question: "Apes and ____ are related but they are not the same.",
                    correctAns: 1,
                    option1ImageName: "monkey",
                    option2ImageName: "lemur",
                    option3ImageName: "sloth",
                    option4ImageName: "koala"),
            Details(question: "A ____ roar is among the most terrifying sounds of the grassland.",
                    correctAns: 2,
                    option1ImageName:"cheetah",
                    option2ImageName: "lion",
                    option3ImageName: "deer",
                    option4ImageName: "tiger"),
            Details(question: "The ____ is the tallest living animal.", 
                    correctAns: 3,
                    option1ImageName: "elephant",
                    option2ImageName: "deer",
                    option3ImageName: "giraffe",
                    option4ImageName: "horse"),
            Details(question: "Some ____ can travel 30 feet in a single jump.",
                    correctAns: 1,
                    option1ImageName: "kangaroo",
                    option2ImageName: "deer",
                    option3ImageName: "rabbit",
                    option4ImageName: "horse"),
            Details(question: "The smallest breeds of ____ are called ponies.", 
                    correctAns: 3,
                    option1ImageName: "zebra",
                    option2ImageName: "donkey",
                    option3ImageName: "horse",
                    option4ImageName: "deer"),
            Details(question: "Giant ____ mostly eat bamboo.",
                    correctAns: 2,
                    option1ImageName: "polarbear",
                    option2ImageName: "panda",
                    option3ImageName: "grizzlybear",
                    option4ImageName: "koala"),
            Details(question: "Most ____ live in northern regions with a cold climate.", 
                    correctAns: 1,
                    option1ImageName: "polarbear",
                    option2ImageName: "grizzlybear",
                    option3ImageName: "panda",
                    option4ImageName: "koala")
        ],
    
    
  
        "Cartoons": [
            Details(question: "Who is the superhero alter ego of Bruce Wayne?", 
                    correctAns: 4,
                    option1ImageName: "hulk",
                    option2ImageName: "spiderman",
                    option3ImageName: "fourarms",
                    option4ImageName: "batman"),
            Details(question: "This character lives in a pineapple under the sea?", 
                    correctAns: 2, 
                    option1ImageName: "patrick",
                    option2ImageName: "spongebob",
                    option3ImageName: "squidward",
                    option4ImageName: "gary"),
            Details(question: "Who is known for their web-shooting abilities?", 
                    correctAns: 3,
                    option1ImageName: "batman",
                    option2ImageName: "hulk",
                    option3ImageName: "spiderman",
                    option4ImageName: "fourarms"),
            Details(question: "Who is the fastest hedgehog in the world?",
                    correctAns: 2,
                    option1ImageName: "tails",
                    option2ImageName: "sonic",
                    option3ImageName: "knuckles",
                    option4ImageName: "shadow"),
            Details(question: "Who sang the song 'Let It Go'?", 
                    correctAns: 4,
                    option1ImageName: "anna",
                    option2ImageName: "belle",
                    option3ImageName: "aurora",
                    option4ImageName: "elsa"),
            Details(question: "Who wields a magical hammer called Mjolnir?", 
                    correctAns: 3,
                    option1ImageName: "spiderman",
                    option2ImageName: "batman",
                    option3ImageName: "thor",
                    option4ImageName: "hulk"),
            Details(question: "Which character ate a poisonous apple?", 
                    correctAns: 1,
                    option1ImageName: "snowwhite",
                    option2ImageName: "cinderella",
                    option3ImageName: "aurora",
                    option4ImageName: "belle"),
            Details(question: "In 'The Lion King,' who is Simba's father?", 
                    correctAns: 1,
                    option1ImageName: "mufasa",
                    option2ImageName: "scar",
                    option3ImageName: "timon",
                    option4ImageName: "sarabi"),
            Details(question: "Which character is the speed-loving racer in 'Cars'?",
                    correctAns: 4,
                    option1ImageName: "mater",
                    option2ImageName: "sally",
                    option3ImageName: "doc",
                    option4ImageName: "mcqueen"),
            Details(question: "Who is the famous mouse created by Walt Disney?", 
                    correctAns: 3,
                    option1ImageName: "jerry",
                    option2ImageName: "shadow",
                    option3ImageName: "mickey",
                    option4ImageName: "sonic")
        ]

]
